image: ubuntu
stack: python 3.8

# we build manually in the install step
build: off

build_script:
- pip install -r requirements.txt
- pip install codecov
- make check

test_script:
- make test coverage
- codecov

